name: Deploy HTML to S3

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-static-site .

      - name: Run tests in Docker
        run: |
          docker run --rm my-static-site test -f /usr/share/nginx/html/index.html

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Upload static site to S3
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            aws s3 sync website/ s3://staticwebperi/ --delete
          else
            aws s3 sync website/ s3://staticwebperi-staging/ --delete
          fi